##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.10.0-B14] date: [Wed Aug 05 16:40:56 BST 2020]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = tail-anchor-firmware


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/config.c \
Core/Src/mqtt_manager.c \
Core/Src/dhcp_options.c \
Core/Src/messages.c \
Core/Src/freertos.c \
Core/Src/radio.c \
Core/Src/radio_spi.c \
Core/Src/stm32f7xx_it.c \
Core/Src/stm32f7xx_hal_msp.c \
Core/Src/stm32f7xx_hal_timebase_tim.c \
LWIP/App/lwip.c \
LWIP/Target/ethernetif.c \
USB_DEVICE/App/usb_device.c \
USB_DEVICE/App/usbd_desc.c \
USB_DEVICE/App/usbd_cdc_if.c \
USB_DEVICE/Target/usbd_conf.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
STM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.c \
Core/Src/system_stm32f7xx.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/list.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/queue.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/timers.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
STM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1/port.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/auth.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/ccp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/chap_ms.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/chap-md5.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/chap-new.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/demand.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/eap.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/eui64.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/fsm.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/ipcp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/ipv6cp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/lcp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/magic.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/mppe.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/multilink.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/ppp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/pppapi.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/pppcrypt.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/pppoe.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/pppol2tp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/pppos.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/upap.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/utils.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/vj.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/bridgeif.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/bridgeif_fdb.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ethernet.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/lowpan6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/lowpan6_ble.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/lowpan6_common.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/slipif.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/zepif.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/netif/ppp/ecp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/tcpip.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/api_lib.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/netifapi.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/if_api.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/api_msg.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/err.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/netdb.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/netbuf.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/api/sockets.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/mem.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/def.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/udp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/init.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/netif.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/sys.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/altcp_alloc.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/tcp_out.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/inet_chksum.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/altcp_tcp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/stats.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/altcp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/timeouts.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/raw.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/tcp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/pbuf.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/memp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ip.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/dns.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/tcp_in.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/inet6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/nd6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_frag.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_addr.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/ethip6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/mld6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/icmp6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/core/ipv6/dhcp6.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/system/OS/sys_arch.c \
STM32CubeF7/Middlewares/Third_Party/LwIP/src/apps/mqtt/mqtt.c \
STM32CubeF7/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
STM32CubeF7/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
STM32CubeF7/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
STM32CubeF7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c  

# ASM sources
ASM_SOURCES =  \
startup_stm32f756xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F756xx


# AS includes
AS_INCLUDES =  \
-ICore/Inc

# C includes
C_INCLUDES =  \
-ICore/Inc \
-Ijsmn \
-ILWIP/App \
-ILWIP/Target \
-IUSB_DEVICE/App \
-IUSB_DEVICE/Target \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/system \
-ISTM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Inc \
-ISTM32CubeF7/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy \
-ISTM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/include \
-ISTM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-ISTM32CubeF7/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/netif/ppp \
-ISTM32CubeF7/Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
-ISTM32CubeF7/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-ISTM32CubeF7/Drivers/CMSIS/Device/ST/STM32F7xx/Include \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/lwip \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/lwip/apps \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/lwip/priv \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/lwip/prot \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/netif \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/compat/posix \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/compat/posix/net \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/src/include/compat/stdc \
-ISTM32CubeF7/Middlewares/Third_Party/LwIP/system/arch \
-ISTM32CubeF7/Drivers/CMSIS/Include \
-ISTM32CubeF7/Drivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -Werror -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F756VGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)


.PHONY: flash
flash:
	sudo dfu-util -a 0 -s 0x08000000:leave -D $(BUILD_DIR)/$(TARGET).bin

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
